[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from  = "/api/*"
  to = "https://brandhub-api.onrender.com"
  status = 200
  force = true
  [redirects.headers]
    X-from = "Netlify"

[[redirects]]
  from = "/auth/token"
  to = "https://brandhub-api.onrender.com"
  status = 200
  force = true
  [redirects.headers]
    X-from = "Netlify"

[[headers]]
  for = "/index.html"
  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''