export const itemTypes = [
  "Banner",
  "Bin",
  "Bin Card",
  "Bottle Topper",
  "Carton Rider",
  "Case Sleeves",
  "Case Stacker",
  "Case Talker",
  "Case Wrap",
  "Ceiling Dangler/Mobile/Inflatables",
  "Channel Strip",
  "Cold Box Acetate",
  "Corrugate Bin",
  "Counter Unit",
  "Coupon Necker",
  "CRider/BTopper Combo",
  "Display Pricer",
  "End Cap Kit",
  "Flyer",
  "Gallo Coupon Pamphlet",
  "Gallo Coupon Tearpad",
  "Gift Box/Gift Bag",
  "Glorifier",
  "Invitation to Purchase",
  "Lama Display",
  "Mass Accessory/Bin/Mass Retrofit",
  "Mass Display",
  "Mini-Mass Display",
  "Miscellaneous - Long Lead Time",
  "Miscellaneous - Short Lead Time",
  "Necker",
  "Necker/Shelf Talker Combo",
  "Pallet Display",
  "Pallet Wrap",
  "Pamphlet",
  "Poster",
  "Post-It Tear Pad",
  "Recipe Pad w/o Coupon",
  "Shelf Pricer",
  "Shelf Talker",
  "Sign",
  "Stand-Up",
  "Stickers",
  "Table Tent / Insert",
  "Tear Pad",
  "Uber Carton Rider",
  "Winemaker Note/Tasting Card",
];

export const brands = [
  "Abandon",
  "Alamos",
  "Amaro Montenegro",
  "Amelia Brut Rose",
  "Andre",
  "Apothic",
  "Arbor Mist",
  "Arch Rival",
  "Athena",
  "Ballatore",
  "Barefoot",
  "Barefoot Bubbly",
  "Barefoot Cellars Box",
  "Barefoot Seltzer",
  "Barefoot Spritzers",
  "Bartles & Jaymes",
  "Bear Flag",
  "Bella Sera",
  "Black Box",
  "Black Box Spirits",
  "Brancaia",
  "Bridlewood",
  "Carlo Rossi",
  "Carlo Rossi Box",
  "Carnivor",
  "Chateau Souverain",
  "Clos Du Bois",
  "Columbia",
  "Cooks",
  "Covey Run",
  "Da Vinci",
  "Dancing Bull",
  "Dark Horse Box",
  "Dark Horse Sparkling",
  "Dark Horse Wine",
  "Department 66",
  "Diplomatico",
  "Don Fulano",
  "Don Miguel Gascon",
  "E&J Flavors",
  "E&J VS Brandy",
  "E&J VSOP Brandy",
  "E&J XO Brandy",
  "Ecco Domani",
  "Edna Valley Vineyard",
  "Ember",
  "Estancia",
  "Familia Camarena",
  "Fleur de Mer",
  "Franciscan",
  "Frei Brothers",
  "Gallo Family Vineyards",
  "Gallo Signature Series",
  "Gather & Grace",
  "Ghost Pines",
  "High Noon Beverage",
  "High Noon",
  "J Vineyards & Winery",
  "J Vineyards Sparkling",
  "Jayson",
  "John Barr",
  "Jura",
  "Kingdom",
  "La Marca",
  "Laguna",
  "Las Rocas",
  "Leftie",
  "Liberty Creek",
  "Livingston Cellars",
  "Locations",
  "Lo-Fi Aperitifs",
  "Louis M Martini",
  "MacMurray Estate Vineyards",
  "Madria Sangria",
  "Maison No. 9",
  "Mark West",
  "Martin Codax",  
  "Maso Canali",
  "Mia Dolcea",
  "Mirassou",
  "Mother",
  "New Amsterdam Gin",
  "New Amsterdam Vodka",
  "Orin Swift",
  "Pahlmeyer",
  "Paul Masson Brandy",
  "Paul Masson Dessrts",
  "Paul Masson Table",
  "Peter Vella",
  "Popular Corporate",
  "Premium Compass Corporate",
  "Premium Compass Portfolio",
  "Premium Renaissance Corporate",
  "Premium Renaissance Portfolio",
  "Prophecy",
  "Rancho Zabaco",
  "Red Rock Winery",
  "Redwood Creek",
  "RumHaven",
  "Saint Clair Family Estate",
  "Select Aperitivo",
  "Shackleton",
  "Spirits Corporate",
  "Starborough",
  "Steamsmith",
  "Storypoint",
  "Sunseeker",
  "Talbott Vineyards",
  "The Dalmore",
  "The Naked Grape",
  "The Naked Grape Box",
  "Thrive",
  "Thunderbird",
  "Tisdale",
  "Totts",
  "Turning Leaf",
  "Vecchia Romagna Brandy",
  "Vin Vault",
  "Whitehaven",
  "William Hill",
]
